### ISSUE TITLE
NullPointerException when changing fragment

### ISSUE THREAD

**Issue by martirius** [ChahatGupta/FadeInTextView-Android#5]
Hi, i'm using your library to print some text in a recycler view (every item has a fade TextView); however when I want to change the fragment to another one, i receive null pointer Exception:
`Process: com.test.roboticbartender, PID: 13486
    kotlin.KotlinNullPointerException
        at com.test.roboticbartender.util.fadeTextView.FadeTextView.getText(FadeTextView.kt:99)
        at android.widget.TextView.getTextForAccessibility(TextView.java:9103)
        at android.widget.TextView.onInitializeAccessibilityNodeInfoInternal(TextView.java:8913)
        at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6084)
        at android.view.View.createAccessibilityNodeInfoInternal(View.java:6043)
        at android.view.View.createAccessibilityNodeInfo(View.java:6028)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1020)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:844)
        at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:156)
        at android.view.AccessibilityInteractionController.-wrap1(AccessibilityInteractionController.java)
        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1191)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5426)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)`

(the class is yours, it has only a different name and a different package)

From debug it comes out that getText is always called, but i don't understand why; so when i change fragment the text became null; it calls gettext and it crash...

**Comment by martirius** [comment]
Resolved by changing  Charsequence to "" instead of null inside the class
